//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocusedObjective.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FocusedObjective.Common.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} feature not implement at this time..
        /// </summary>
        public static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read license. Please check the license entry and contact FocusedObjective.com support if you believe you have a valid license file. Remove the &apos;&lt;?xml...&apos; declaration line from the top of your file if it exists..
        /// </summary>
        public static string Error11 {
            get {
                return ResourceManager.GetString("Error11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License signature match fail. The license text doesn&apos;t match the signature. This occurs if the license text has been modified from its original content..
        /// </summary>
        public static string Error12 {
            get {
                return ResourceManager.GetString("Error12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No license element found..
        /// </summary>
        public static string Error13 {
            get {
                return ResourceManager.GetString("Error13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No license element. Using free license which is limited in functionality. Go to focusedobjective.com to request a trial or buy a fully featured license..
        /// </summary>
        public static string Error14 {
            get {
                return ResourceManager.GetString("Error14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License limits the number of simulation cycles to {0}. Go to focusedobjective.com and request a trial license or purchase a full license..
        /// </summary>
        public static string Error15 {
            get {
                return ResourceManager.GetString("Error15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License doesn&apos;t have the {0} feature enabled. Go to focusedobjective.com and request a trial license or purchase a full license..
        /// </summary>
        public static string Error16 {
            get {
                return ResourceManager.GetString("Error16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License has expired.  Go to focusedobjective.com and request a trial license or purchase a full license..
        /// </summary>
        public static string Error17 {
            get {
                return ResourceManager.GetString("Error17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value for &apos;occurrenceHighBound&apos; must be greater than the value for &apos;occurrenceLowBound&apos; for the added scope section named {0}..
        /// </summary>
        public static string Error18 {
            get {
                return ResourceManager.GetString("Error18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value for &apos;estimateHighBound&apos; must be greater than the value for &apos;estimateLowBound&apos; for the blocking event section named {0}..
        /// </summary>
        public static string Error19 {
            get {
                return ResourceManager.GetString("Error19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation did not complete within {0} simulation intervals. This is either due to a model error, or due to the &apos;limitIntervalsTo&apos; attribute value of the &apos;execute&apos; section being too low..
        /// </summary>
        public static string Error2 {
            get {
                return ResourceManager.GetString("Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value for &apos;occurrenceHighBound&apos; must be greater than the value for &apos;occurrenceLowBound&apos; for the blocking event section named {0}..
        /// </summary>
        public static string Error20 {
            get {
                return ResourceManager.GetString("Error20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No setup/columns/column Id found that matches the specified columnId for the blocking event section named {0}..
        /// </summary>
        public static string Error21 {
            get {
                return ResourceManager.GetString("Error21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No setup/columns/column Id or startsInColumnId found that matches the specified columnId for the defect section named {0}..
        /// </summary>
        public static string Error22 {
            get {
                return ResourceManager.GetString("Error22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value for &apos;occurrenceHighBound&apos; must be greater than (or equal) the value for &apos;occurrenceLowBound&apos; for the defect section named {0}..
        /// </summary>
        public static string Error23 {
            get {
                return ResourceManager.GetString("Error23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No setup/columns/column Id found that matches the specified columnId in the setup/defects/defect/column section with id={0}..
        /// </summary>
        public static string Error24 {
            get {
                return ResourceManager.GetString("Error24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value for &apos;estimateHighBound&apos; must be greater than the value for &apos;estimateLowBound&apos; in the setup/defects/defect/column section with id={0}..
        /// </summary>
        public static string Error25 {
            get {
                return ResourceManager.GetString("Error25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value for &apos;estimateHighBound&apos; must be greater than the value for &apos;estimateLowBound&apos; for the custom backlog section entry named {0}..
        /// </summary>
        public static string Error26 {
            get {
                return ResourceManager.GetString("Error26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value for &apos;percentageHighBound&apos; must be greater than the value for &apos;percentageLowBound&apos; for the custom backlog section entry named {0}..
        /// </summary>
        public static string Error27 {
            get {
                return ResourceManager.GetString("Error27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value for &apos;estimateHighBound&apos; must be greater than the value for &apos;estimateLowBound&apos; for the setup/backlog/custom/column section entry with id={0}..
        /// </summary>
        public static string Error28 {
            get {
                return ResourceManager.GetString("Error28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No setup/columns/column Id found that matches the specified columnId for the setup/backlog/custom/column section entry with id={0}..
        /// </summary>
        public static string Error29 {
            get {
                return ResourceManager.GetString("Error29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing mandatory element: &apos;{0}&apos;.
        /// </summary>
        public static string Error3 {
            get {
                return ResourceManager.GetString("Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date format specified in &apos;{0}&apos; section. Please format dates to be in the YYYYMMDD format or the format specifiec in the &apos;dateFormat&apos; attribute of the &apos;execute&apos; section..
        /// </summary>
        public static string Error30 {
            get {
                return ResourceManager.GetString("Error30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;workdays&apos; attribute cannot be an empty string for the execute/forecastDate section. This value is a comma-separated list of days of the week that work will occur. For example &quot;monday,tuesday,wednesday,thursday,friday&quot;..
        /// </summary>
        public static string Error31 {
            get {
                return ResourceManager.GetString("Error31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;workdays&apos; attribute is invalid for the execute/forecastDate section. This value is a comma-separated list of days of the week that work will occur. For example &quot;monday,tuesday,wednesday,thursday,friday&quot;..
        /// </summary>
        public static string Error32 {
            get {
                return ResourceManager.GetString("Error32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value for &apos;estimateHighBound&apos; must be greater than the value for &apos;estimateLowBound&apos; for the defect section named {0}..
        /// </summary>
        public static string Error33 {
            get {
                return ResourceManager.GetString("Error33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value for &apos;estimateHighBound&apos; must be greater than the value for &apos;estimateLowBound&apos; for the Added Scope section named {0}..
        /// </summary>
        public static string Error34 {
            get {
                return ResourceManager.GetString("Error34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save video file to location {0}. Save failed with the error message: {1}.
        /// </summary>
        public static string Error35 {
            get {
                return ResourceManager.GetString("Error35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensitivity type must be iterations when simulating Scrum. Simulation type set to Iterations. .
        /// </summary>
        public static string Error36 {
            get {
                return ResourceManager.GetString("Error36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough distribution arguments specified for distribution. This distribution requires at least {0} arguments..
        /// </summary>
        public static string Error37 {
            get {
                return ResourceManager.GetString("Error37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid distribution argument. Argument number {0} in the argument string {1} could not be converted to a number..
        /// </summary>
        public static string Error38 {
            get {
                return ResourceManager.GetString("Error38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid distribution argument. Argument number {0} is an invalid value for the distribution..
        /// </summary>
        public static string Error39 {
            get {
                return ResourceManager.GetString("Error39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing mandatory attribute &apos;{0}&apos; for element &apos;{1}&apos;.
        /// </summary>
        public static string Error4 {
            get {
                return ResourceManager.GetString("Error4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters for the &apos;{0}&apos; distribution are: {1}. See {2} for more information..
        /// </summary>
        public static string Error40 {
            get {
                return ResourceManager.GetString("Error40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing optional attribute &apos;{0}&apos; for element &apos;{1}&apos;. Default used &apos;{2}&apos;.
        /// </summary>
        public static string Error41 {
            get {
                return ResourceManager.GetString("Error41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for attribute &apos;{0}&apos; for element &apos;{1}&apos;. &apos;{2}&apos; is not recognized or valid..
        /// </summary>
        public static string Error42 {
            get {
                return ResourceManager.GetString("Error42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; for element &apos;{1}&apos; must have a value greater than {2}..
        /// </summary>
        public static string Error43 {
            get {
                return ResourceManager.GetString("Error43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value for &apos;estimateHighBound&apos; must be greater than the value for &apos;estimateLowBound&apos; for the column named &apos;{0}&apos; with an id={1} ..
        /// </summary>
        public static string Error44 {
            get {
                return ResourceManager.GetString("Error44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value for &apos;maxWip&apos; must be greater than the value for &apos;minWip&apos; for the execute/addStaff/column with an id={0}..
        /// </summary>
        public static string Error45 {
            get {
                return ResourceManager.GetString("Error45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No setup/columns/column Id found that matched the specified Id in the execute/addStaff/column with an id={0}..
        /// </summary>
        public static string Error46 {
            get {
                return ResourceManager.GetString("Error46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No distribution with the name &apos;{0}&apos; is defined in the setup/distributions section for the {1} section named {2}..
        /// </summary>
        public static string Error47 {
            get {
                return ResourceManager.GetString("Error47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value for &apos;endPercentage&apos; must be greater than the value for &apos;startPercentage&apos; for the phase section entry named {0}..
        /// </summary>
        public static string Error48 {
            get {
                return ResourceManager.GetString("Error48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; for element &apos;{1}&apos; must have a value less than {2}..
        /// </summary>
        public static string Error49 {
            get {
                return ResourceManager.GetString("Error49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one &apos;{0}&apos; sub-element is needed.
        /// </summary>
        public static string Error5 {
            get {
                return ResourceManager.GetString("Error5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is recommended that all {0} sections have a name..
        /// </summary>
        public static string Error50 {
            get {
                return ResourceManager.GetString("Error50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phase named &apos;{0}&apos; overlaps with the phase named &apos;{1}&apos;. There can be no overlap in start and end attribute values between phases..
        /// </summary>
        public static string Error51 {
            get {
                return ResourceManager.GetString("Error51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date format specified in &apos;{0}&apos; section named &apos;{1}&apos;. Please format dates to be in the YYYYMMDD format or the format specifiec in the &apos;dateFormat&apos; attribute of the &apos;execute&apos; section..
        /// </summary>
        public static string Error52 {
            get {
                return ResourceManager.GetString("Error52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No default class of service specified in &apos;setup/classOfServices&apos;. Add a default=&quot;true&quot; to one of the defined classes of services that will be used if no class of service is specified..
        /// </summary>
        public static string Error53 {
            get {
                return ResourceManager.GetString("Error53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No class of service named &apos;{0}&apos; can be found in the section &apos;{1}&apos; named &apos;{2}&apos;..
        /// </summary>
        public static string Error54 {
            get {
                return ResourceManager.GetString("Error54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid numeric value for attribute &apos;{0}&apos; in element &apos;{1}&apos;. &apos;{2}&apos; is not recognized as a numerical value..
        /// </summary>
        public static string Error55 {
            get {
                return ResourceManager.GetString("Error55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create &apos;{0}&apos; distribution named &apos;{1}&apos;. No valid samples, or a non-numeric sample were found or the supplied &apos;Count&apos; attribute was less than zero. Count must be greater than 0 and samples must be numeric and  separated by &apos;|&apos; or a new-line character, or a &apos;,&apos; for locales that do not use that symbol as a decimal separator..
        /// </summary>
        public static string Error56 {
            get {
                return ResourceManager.GetString("Error56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid variable name. Variable can only contain upper and lowercase letters (a-Z) and underscore (_)characters..
        /// </summary>
        public static string Error57 {
            get {
                return ResourceManager.GetString("Error57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value for &apos;end&apos; must be greater than the value for &apos;start&apos; for the phase section entry named {0}..
        /// </summary>
        public static string Error58 {
            get {
                return ResourceManager.GetString("Error58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula error &apos;{3}&apos; returned for attribute value for &apos;{0}&apos; in element &apos;{1}&apos;. Formula was: &apos;{2}&apos;.
        /// </summary>
        public static string Error59 {
            get {
                return ResourceManager.GetString("Error59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Kanban simulation, at least one &apos;column&apos; entry in the &apos;columns&apos; section needs to be defined.
        /// </summary>
        public static string Error6 {
            get {
                return ResourceManager.GetString("Error6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No setup/columns/column Id found that matches the specified &apos;initialColumn&apos; for the setup/backlog/custom section entry initialColumn={0}..
        /// </summary>
        public static string Error60 {
            get {
                return ResourceManager.GetString("Error60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more deliverables &apos;{0}&apos; cannot be found in setup/backlog/deliverable section for the {1} section named {2}..
        /// </summary>
        public static string Error61 {
            get {
                return ResourceManager.GetString("Error61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No custom backlog named &apos;{0}&apos; can be found in the section &apos;{1}&apos; for the addedScope named &apos;{2}&apos;..
        /// </summary>
        public static string Error62 {
            get {
                return ResourceManager.GetString("Error62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backlog deliverable named &apos;{0}&apos; can be found in the section &apos;{1}&apos; for the addedScope named &apos;{2}&apos;..
        /// </summary>
        public static string Error63 {
            get {
                return ResourceManager.GetString("Error63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No custom backlog named &apos;{0}&apos; can be found in the section &apos;{1}&apos; for the defect named &apos;{2}&apos;..
        /// </summary>
        public static string Error64 {
            get {
                return ResourceManager.GetString("Error64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backlog deliverable named &apos;{0}&apos; can be found in the section &apos;{1}&apos; for the defect named &apos;{2}&apos;..
        /// </summary>
        public static string Error65 {
            get {
                return ResourceManager.GetString("Error65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No custom backlog named &apos;{0}&apos; can be found in the section &apos;{1}&apos; for the blockingEvent named &apos;{2}&apos;..
        /// </summary>
        public static string Error66 {
            get {
                return ResourceManager.GetString("Error66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backlog deliverable named &apos;{0}&apos; can be found in the section &apos;{1}&apos; for the blockingEvent named &apos;{2}&apos;..
        /// </summary>
        public static string Error67 {
            get {
                return ResourceManager.GetString("Error67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; for element &apos;{1}&apos; must have a value greater than or equal {2}..
        /// </summary>
        public static string Error68 {
            get {
                return ResourceManager.GetString("Error68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more phases &apos;{0}&apos; cannot be found in setup/phases section for the {1} section named {2}..
        /// </summary>
        public static string Error7 {
            get {
                return ResourceManager.GetString("Error7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;id&apos; values must be unique. Duplicate column id values are not allowed. Column id values can be any integer value, with columns being ordered left to right from lowest to highest id value. They are used as references when defining events..
        /// </summary>
        public static string Error8 {
            get {
                return ResourceManager.GetString("Error8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value for &apos;{0}&apos; in element &apos;{1}&apos; changed from &apos;{2}&apos; to &apos;{3}&apos;.
        /// </summary>
        public static string Info1 {
            get {
                return ResourceManager.GetString("Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for variable &apos;{0}&apos; changed from &apos;{1}&apos; to &apos;{2}&apos;.
        /// </summary>
        public static string Info2 {
            get {
                return ResourceManager.GetString("Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No column could be adjusted to achieve goal. Add more movable wip limit columns to the addStaff command, or increase the maxWip attribute for a column..
        /// </summary>
        public static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
    }
}
