/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForecasterThroughputRouteImport } from './routes/forecaster/throughput'
import { Route as ForecasterStoryCountRouteImport } from './routes/forecaster/story-count'
import { Route as ForecasterMultiFeatureRouteImport } from './routes/forecaster/multi-feature'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecasterThroughputRoute = ForecasterThroughputRouteImport.update({
  id: '/forecaster/throughput',
  path: '/forecaster/throughput',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecasterStoryCountRoute = ForecasterStoryCountRouteImport.update({
  id: '/forecaster/story-count',
  path: '/forecaster/story-count',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecasterMultiFeatureRoute = ForecasterMultiFeatureRouteImport.update({
  id: '/forecaster/multi-feature',
  path: '/forecaster/multi-feature',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forecaster/multi-feature': typeof ForecasterMultiFeatureRoute
  '/forecaster/story-count': typeof ForecasterStoryCountRoute
  '/forecaster/throughput': typeof ForecasterThroughputRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forecaster/multi-feature': typeof ForecasterMultiFeatureRoute
  '/forecaster/story-count': typeof ForecasterStoryCountRoute
  '/forecaster/throughput': typeof ForecasterThroughputRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forecaster/multi-feature': typeof ForecasterMultiFeatureRoute
  '/forecaster/story-count': typeof ForecasterStoryCountRoute
  '/forecaster/throughput': typeof ForecasterThroughputRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forecaster/multi-feature'
    | '/forecaster/story-count'
    | '/forecaster/throughput'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forecaster/multi-feature'
    | '/forecaster/story-count'
    | '/forecaster/throughput'
  id:
    | '__root__'
    | '/'
    | '/forecaster/multi-feature'
    | '/forecaster/story-count'
    | '/forecaster/throughput'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForecasterMultiFeatureRoute: typeof ForecasterMultiFeatureRoute
  ForecasterStoryCountRoute: typeof ForecasterStoryCountRoute
  ForecasterThroughputRoute: typeof ForecasterThroughputRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecaster/throughput': {
      id: '/forecaster/throughput'
      path: '/forecaster/throughput'
      fullPath: '/forecaster/throughput'
      preLoaderRoute: typeof ForecasterThroughputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecaster/story-count': {
      id: '/forecaster/story-count'
      path: '/forecaster/story-count'
      fullPath: '/forecaster/story-count'
      preLoaderRoute: typeof ForecasterStoryCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecaster/multi-feature': {
      id: '/forecaster/multi-feature'
      path: '/forecaster/multi-feature'
      fullPath: '/forecaster/multi-feature'
      preLoaderRoute: typeof ForecasterMultiFeatureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForecasterMultiFeatureRoute: ForecasterMultiFeatureRoute,
  ForecasterStoryCountRoute: ForecasterStoryCountRoute,
  ForecasterThroughputRoute: ForecasterThroughputRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
