/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WrongOrderRouteImport } from './routes/wrong-order'
import { Route as VotingRouteImport } from './routes/voting'
import { Route as ThroughputRouteImport } from './routes/throughput'
import { Route as TeamDashboardRouteImport } from './routes/team-dashboard'
import { Route as StoryCountRouteImport } from './routes/story-count'
import { Route as SimmlReferenceRouteImport } from './routes/simml-reference'
import { Route as MultiFeatureRouteImport } from './routes/multi-feature'
import { Route as LatentDefectRouteImport } from './routes/latent-defect'
import { Route as KanbanScrumSimRouteImport } from './routes/kanban-scrum-sim'
import { Route as CapabilityMatrixRouteImport } from './routes/capability-matrix'
import { Route as IndexRouteImport } from './routes/index'

const WrongOrderRoute = WrongOrderRouteImport.update({
  id: '/wrong-order',
  path: '/wrong-order',
  getParentRoute: () => rootRouteImport,
} as any)
const VotingRoute = VotingRouteImport.update({
  id: '/voting',
  path: '/voting',
  getParentRoute: () => rootRouteImport,
} as any)
const ThroughputRoute = ThroughputRouteImport.update({
  id: '/throughput',
  path: '/throughput',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamDashboardRoute = TeamDashboardRouteImport.update({
  id: '/team-dashboard',
  path: '/team-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryCountRoute = StoryCountRouteImport.update({
  id: '/story-count',
  path: '/story-count',
  getParentRoute: () => rootRouteImport,
} as any)
const SimmlReferenceRoute = SimmlReferenceRouteImport.update({
  id: '/simml-reference',
  path: '/simml-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiFeatureRoute = MultiFeatureRouteImport.update({
  id: '/multi-feature',
  path: '/multi-feature',
  getParentRoute: () => rootRouteImport,
} as any)
const LatentDefectRoute = LatentDefectRouteImport.update({
  id: '/latent-defect',
  path: '/latent-defect',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanScrumSimRoute = KanbanScrumSimRouteImport.update({
  id: '/kanban-scrum-sim',
  path: '/kanban-scrum-sim',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilityMatrixRoute = CapabilityMatrixRouteImport.update({
  id: '/capability-matrix',
  path: '/capability-matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capability-matrix': typeof CapabilityMatrixRoute
  '/kanban-scrum-sim': typeof KanbanScrumSimRoute
  '/latent-defect': typeof LatentDefectRoute
  '/multi-feature': typeof MultiFeatureRoute
  '/simml-reference': typeof SimmlReferenceRoute
  '/story-count': typeof StoryCountRoute
  '/team-dashboard': typeof TeamDashboardRoute
  '/throughput': typeof ThroughputRoute
  '/voting': typeof VotingRoute
  '/wrong-order': typeof WrongOrderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capability-matrix': typeof CapabilityMatrixRoute
  '/kanban-scrum-sim': typeof KanbanScrumSimRoute
  '/latent-defect': typeof LatentDefectRoute
  '/multi-feature': typeof MultiFeatureRoute
  '/simml-reference': typeof SimmlReferenceRoute
  '/story-count': typeof StoryCountRoute
  '/team-dashboard': typeof TeamDashboardRoute
  '/throughput': typeof ThroughputRoute
  '/voting': typeof VotingRoute
  '/wrong-order': typeof WrongOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capability-matrix': typeof CapabilityMatrixRoute
  '/kanban-scrum-sim': typeof KanbanScrumSimRoute
  '/latent-defect': typeof LatentDefectRoute
  '/multi-feature': typeof MultiFeatureRoute
  '/simml-reference': typeof SimmlReferenceRoute
  '/story-count': typeof StoryCountRoute
  '/team-dashboard': typeof TeamDashboardRoute
  '/throughput': typeof ThroughputRoute
  '/voting': typeof VotingRoute
  '/wrong-order': typeof WrongOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capability-matrix'
    | '/kanban-scrum-sim'
    | '/latent-defect'
    | '/multi-feature'
    | '/simml-reference'
    | '/story-count'
    | '/team-dashboard'
    | '/throughput'
    | '/voting'
    | '/wrong-order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capability-matrix'
    | '/kanban-scrum-sim'
    | '/latent-defect'
    | '/multi-feature'
    | '/simml-reference'
    | '/story-count'
    | '/team-dashboard'
    | '/throughput'
    | '/voting'
    | '/wrong-order'
  id:
    | '__root__'
    | '/'
    | '/capability-matrix'
    | '/kanban-scrum-sim'
    | '/latent-defect'
    | '/multi-feature'
    | '/simml-reference'
    | '/story-count'
    | '/team-dashboard'
    | '/throughput'
    | '/voting'
    | '/wrong-order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapabilityMatrixRoute: typeof CapabilityMatrixRoute
  KanbanScrumSimRoute: typeof KanbanScrumSimRoute
  LatentDefectRoute: typeof LatentDefectRoute
  MultiFeatureRoute: typeof MultiFeatureRoute
  SimmlReferenceRoute: typeof SimmlReferenceRoute
  StoryCountRoute: typeof StoryCountRoute
  TeamDashboardRoute: typeof TeamDashboardRoute
  ThroughputRoute: typeof ThroughputRoute
  VotingRoute: typeof VotingRoute
  WrongOrderRoute: typeof WrongOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wrong-order': {
      id: '/wrong-order'
      path: '/wrong-order'
      fullPath: '/wrong-order'
      preLoaderRoute: typeof WrongOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voting': {
      id: '/voting'
      path: '/voting'
      fullPath: '/voting'
      preLoaderRoute: typeof VotingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/throughput': {
      id: '/throughput'
      path: '/throughput'
      fullPath: '/throughput'
      preLoaderRoute: typeof ThroughputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-dashboard': {
      id: '/team-dashboard'
      path: '/team-dashboard'
      fullPath: '/team-dashboard'
      preLoaderRoute: typeof TeamDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-count': {
      id: '/story-count'
      path: '/story-count'
      fullPath: '/story-count'
      preLoaderRoute: typeof StoryCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simml-reference': {
      id: '/simml-reference'
      path: '/simml-reference'
      fullPath: '/simml-reference'
      preLoaderRoute: typeof SimmlReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-feature': {
      id: '/multi-feature'
      path: '/multi-feature'
      fullPath: '/multi-feature'
      preLoaderRoute: typeof MultiFeatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latent-defect': {
      id: '/latent-defect'
      path: '/latent-defect'
      fullPath: '/latent-defect'
      preLoaderRoute: typeof LatentDefectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban-scrum-sim': {
      id: '/kanban-scrum-sim'
      path: '/kanban-scrum-sim'
      fullPath: '/kanban-scrum-sim'
      preLoaderRoute: typeof KanbanScrumSimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capability-matrix': {
      id: '/capability-matrix'
      path: '/capability-matrix'
      fullPath: '/capability-matrix'
      preLoaderRoute: typeof CapabilityMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapabilityMatrixRoute: CapabilityMatrixRoute,
  KanbanScrumSimRoute: KanbanScrumSimRoute,
  LatentDefectRoute: LatentDefectRoute,
  MultiFeatureRoute: MultiFeatureRoute,
  SimmlReferenceRoute: SimmlReferenceRoute,
  StoryCountRoute: StoryCountRoute,
  TeamDashboardRoute: TeamDashboardRoute,
  ThroughputRoute: ThroughputRoute,
  VotingRoute: VotingRoute,
  WrongOrderRoute: WrongOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
